import type { Metadata } from "next";
import {Inter , Kanit , Prompt , Sarabun} from "next/font/google";
import "./globals.css";



const inter = Inter({subsets: ["latin"],display: "swap",variable: "--font-inter",});
const kanit = Kanit({ subsets: ["thai", "latin"], weight: ["400", "600"] });
const prompt = Prompt({ subsets: ["thai", "latin"], weight: ["400", "500"] });
const sarabun = Sarabun({ subsets: ["thai", "latin"], weight: ["400", "600"] });

export const metadata: Metadata = {
  title: "Demo-TRG2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-zinc-950 text-white">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
